import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import TodoPanel from "../components/todopanel/todopanel";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<TodoPanel />
		</div>
	);
};

export default Home;
